# Default configurations for models used in the experiments that configure the SNN__LOGN_GTV algorithm.
HORPCA:
  label: "HoRPCA"
  color: '#5F3C30'
  linestyle: '-'
  linewidth: 1.5
HORPCA_F:
  label: "HoRPCA-f"
  color: '#A46750'
  linestyle: '--'
  linewidth: 1.5
SNN_L1_GTVS:
  label: "[SNN]-[L1+GTV(S)]"
  color: '#DA4C4C'
  linestyle: '-'
  linewidth: 1.5
SNN_L1_GTVS:
  label: "[SNN]-[L1+GTV(S)]"
  color: '#B00101'
  linestyle: '-'
  linewidth: 1.5
SNN_L1_GTVS_F:
  label: "[SNN]-[L1+GTV(S)]-f"
  color: '#DA4C4C'
  linestyle: '--'
  linewidth: 1.5
SNN_LOGNSN:
  label: "[SNN]-[LOGN(S-N)]"
  color: '#395F9C'
  linestyle: '-'
  linewidth: 1.5
SNN_LOGNSN_F:
  label: "[SNN]-[LOGN(S-N)]-f"
  color: '#5387DD'
  linestyle: '--'
  linewidth: 1.5
SNN_L1_GTVT_F:
  label: "[SNN]-[L1+GTV(T)]-f" #[SNN]-[LOGN(T-E)]-f"
  color: '#E209E7' #0299B7'
  linestyle: '--'
  linewidth: 1.5
SNN_LOGNTE_F:
  label: "[SNN]-[LOGN(T-E)]-f"
  color: '#0299B7'
  linestyle: '--'
  linewidth: 1.5
SNN_LOGNTE_GTVT_F:
  label: "[SNN]-[LOGN(T-E)+GTV(T)]-f"
  color: '#400A8B'
  linestyle: '--'
  linewidth: 1.5
SNN_LOGNSTN_F:
  label: '[SNN]-[LOGN(ST-N)]-f'
  color: "#6125AF"
  linestyle: '--'
  linewidth: 1.5
SNN_L1_GTVST_F:
  label: '[SNN]-[L1+GTV(ST)]-f'
  color: "#A12864"
  linestyle: '--'
  linewidth: 1.5
SNN_LOGNSN_GTVT_F:
  label: '[SNN]-[LOGN(S-N)+GTV(T)]-f'
  color: "#479A5F"
  linestyle: '--'
  linewidth: 1.5

# SNN_LOGNSN_GTVS:
#   model: "SNN_LOGN_GTV"
#   name: "[SNN]-[LOGN(S-N)+GTV(S)]"
SNN_LOGNSN_GTVS_F:
  label: "[SNN]-[LOGN(S-N)+GTV(S)]-f"
  color: '#5F8B4C'
  linestyle: '--'
  linewidth: 1.5
# SNN_LOGNTE:
#   model: "SNN_LOGN_GTV"
#   name: "[SNN]-[LOGN(T-E)]-f"
  
# SNN_L1_GTVT_F:
#   model: "SNN_LOGN_GTV"
#   name: "[SNN]-[L1+GTV(T)]-f"
  
# SNN_LOGNTE_GTVT_F:
#   model: "SNN_LOGN_GTV"
#   name: "[SNN]-[LOGN(T-E)+GTV(T)]-f"
  