"HoRPCA":
  model: "SNN_LOGN_GTV"
  name: "HoRPCA"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 0
  weighing: 'size_normalized' # 'size_normalized_inv'
  err_tol: 0.005
  max_iter: 500 #5000
  rho_update: 'domain_parametrization'
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config: []
"HoRPCA-f":
  model: "SNN_LOGN_GTV"
  name: "HoRPCA-f"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 0
  soft_constrained: True
  weighing: 'size_normalized_inv'
  err_tol: 0.05
  max_iter: 5000
  rho_update: 'domain_parametrization'
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config: []
  hyperparameters:
    lda_f: 1.0
"LR-STS_f":
  model: "SNN_LOGN_GTV"
  name: "LR-STS_f"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 0
  soft_constrained: True
  weighing: 'size_normalized_inv'
  err_tol: 0.1
  max_iter: 2000
  rho_update: 'domain_parametrization'
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: ~
  gtvr_config:
    - graph: 'temporal'
      mode : [4]
      p: 1
      variation_type: GTV
      normalization: 'none'
  hyperparameters:
    lda_f: 1.0
"LR-STS":
  model: "SNN_LOGN_GTV"
  name: "LR-STS"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 0
  soft_constrained: False
  weighing: 'size_normalized_inv'
  err_tol: 0.01
  max_iter: 5000
  rho_update: 'domain_parametrization'
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: ~
  gtvr_config:
    - graph: 'temporal'
      mode : [4]
      p: 1
      variation_type: GTV
      normalization: 'none'
"LR-SSS_f":
  model: "SNN_LOGN_GTV"
  name: "LR-SSS_f"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 0
  soft_constrained: True
  weighing: 'size_normalized_inv'
  err_tol: 0.1
  max_iter: 2000
  rho_update: 'domain_parametrization'
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: ~
  gtvr_config:
    - graph: 'spatial'
      mode : [1]
      p: 1
      variation_type: GTMV
      normalization: 'none'
  hyperparameters:
    lda_f: 1.0
"LR-SSS":
  model: "SNN_LOGN_GTV"
  name: "LR-SSS_f"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 0
  soft_constrained: False
  weighing: 'size_normalized_inv'
  err_tol: 0.1
  max_iter: 2000
  rho_update: 'domain_parametrization'
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: ~
  gtvr_config:
    - graph: 'spatial'
      mode : [1]
      p: 1
      variation_type: GTMV
      normalization: 'none'
  hyperparameters:
    lda_f: 1.0
"LR-STSS_f":
  model: "SNN_LOGN_GTV"
  name: "LR-STSS_f"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 0
  soft_constrained: True
  weighing: 'size_normalized_inv'
  err_tol: 0.1
  max_iter: 2000
  rho_update: 'domain_parametrization'
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: ~
  gtvr_config:
    - graph: 'spatial'
      mode : [1]
      p: 1
      variation_type: GTMV
      normalization: 'none'
    - graph: 'temporal'
      mode : [4]
      p: 1
      variation_type: GTV
      normalization: 'none'
  hyperparameters:
    lda_f: 1.0
"LR-STSS":
  model: "SNN_LOGN_GTV"
  name: "LR-STSS"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 0
  soft_constrained: False
  weighing: 'size_normalized_inv'
  err_tol: 0.1
  max_iter: 2000
  rho_update: 'domain_parametrization'
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: ~
  gtvr_config:
    - graph: 'spatial'
      mode : [1]
      p: 1
      variation_type: GTMV
      normalization: 'none'
    - graph: 'temporal'
      mode : [4]
      p: 1
      variation_type: GTV
      normalization: 'none'
  hyperparameters:
    lda_f: 1.0
# "LR-STS":
  # SNN_L1_GTV_T:
  #   model: "SNN_LOGN_GTV"
  #   name: "[SNN]-[L1+GTV(T)]"
  #   lr_modes: [1, 2, 3]
  #   graph_modes: [1]
  #   graph: 'spatial'
  #   grouping: 'neighbor'
  #   r_hop: 0
  #   weighing: 'size_normalized_inv'
  #   err_tol: 0.1
  #   max_iter: 200
  #   rho_update: 'domain_parametrization'
  #   rho_update_thr: 100
  #   verbose: 0
  #   lda_gtvs: [] 
  #   gtvr_config:
  #     - graph: 'temporal'
  #       mode : [3]
  #       p: 1
  #       variation_type: GTV
  # SNN_L1_GTV_ST:
  #   model: "SNN_LOGN_GTV"
  #   name: "[SNN]-[L1+GTV(ST)]"
  #   lr_modes: [1, 2, 3]
  #   graph_modes: [1,3]
  #   graph: 'spatio-temporal'
  #   grouping: 'neighbor'
  #   r_hop: 0
  #   weighing: 'size_normalized_inv'
  #   err_tol: 0.1
  #   max_iter: 100
  #   rho_update: 1
  #   rho_update_thr: 100
  #   verbose: 0
  #   lda_gtvs: [] 
  #   gtvr_config:
  #     - graph: 'spatial'
  #       mode : [1,3]
  #       p: 2
  #       variation_type: GTV
SNN_LOGN:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[LOGN(S-N)]"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 1
  weighing: 'size_normalized_inv'
  err_tol: 0.005
  max_iter: 500 # 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config: []
SNN_LOGN_sn:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[LOGN(S-N)]_sn"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 1
  weighing: 'size_normalized'
  err_tol: 0.005
  max_iter: 500 # 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config: []
SNN_LOGN_SN_GTV_T:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[LOGN(S-N)+GTV(T)]"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 1
  weighing: 'size_normalized_inv'
  err_tol: 0.005
  max_iter: 500 # 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config:
    - graph: 'temporal'
      mode : [4]
      p: 1
      variation_type: GTV
      normalization: 'none'
SNN_LOGN_SN_GTV_T_sn:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[LOGN(S-N)+GTV(T)]_sn"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 1
  weighing: 'size_normalized'
  err_tol: 0.005
  max_iter: 500 # 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config:
    - graph: 'temporal'
      mode : [4]
      p: 1
      variation_type: GTV
      normalization: 'none'
SNN_LOGN_SN_GTV_S:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[LOGN(S-N)+GTV(S)]"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 1
  weighing: 'size_normalized'
  err_tol: 0.005
  max_iter: 500 # 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config:
    - graph: 'spatial'
      mode : [1]
      p: 2
      variation_type: GTV
      normalization: 'out_degree'
SNN_LOGNTE:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[LOGN(T-E)]"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [4]
  graph: 'temporal'
  grouping: 'edge'
  r_hop: 1
  weighing: 'size_normalized_inv'
  err_tol: 0.005
  max_iter: 500 # 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config: []
SNN_LOGNTE_sn:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[LOGN(T-E)]_sn"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [4]
  graph: 'temporal'
  grouping: 'edge'
  r_hop: 1
  weighing: 'size_normalized'
  err_tol: 0.005
  max_iter: 500 # 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config: []
SNN_L1_GTV_T:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[L1+GTV(T)]"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 0
  soft_constrained: False
  weighing: 'size_normalized_inv'
  err_tol: 0.005
  max_iter: 500 # 5000
  rho_update: 'domain_parametrization'
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: ~
  gtvr_config:
    - graph: 'temporal'
      mode : [4]
      p: 1
      variation_type: GTV
      normalization: 'none'
SNN_L1_GTV_T_sn:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[L1+GTV(T)]"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 0
  soft_constrained: False
  weighing: 'size_normalized'
  err_tol: 0.005
  max_iter: 500 # 5000
  rho_update: 'domain_parametrization'
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: ~
  gtvr_config:
    - graph: 'temporal'
      mode : [4]
      p: 1
      variation_type: GTV
      normalization: 'none'
SNN_LOGNST:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[LOGN(ST-N)]"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1,4]
  graph: 'spatio-temporal'
  grouping: 'neighbor'
  r_hop: 1
  weighing: 'size_normalized_inv'
  err_tol: 0.005
  max_iter: 500 # 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config: []
SNN_LOGNST_sn:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[LOGN(ST-N)]_sn"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1,4]
  graph: 'spatio-temporal'
  grouping: 'neighbor'
  r_hop: 1
  weighing: 'size_normalized'
  err_tol: 0.005
  max_iter: 500 # 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config: []
SNN_LOGNST_GTVST:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[LOGN(ST-N)+GTV(ST)]"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1,4]
  graph: 'spatio-temporal'
  grouping: 'neighbor'
  r_hop: 1
  weighing: 'size_normalized'
  err_tol: 0.005
  max_iter: 500 # 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config:
  - graph: 'spatial'
    mode : [1,4]
    p: 2
    variation_type: GTV
    normalization: 'out_degree'
SNN_LOGNST_GTVT:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[LOGN(ST-N)+GTV(S)]"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1,4]
  graph: 'spatio-temporal'
  grouping: 'neighbor'
  r_hop: 1
  weighing: 'size_normalized'
  err_tol: 0.005
  max_iter: 500 # 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config:
  - graph: 'temporal'
    mode : [4]
    p: 1
    variation_type: GTV
    normalization: 'none'
SNN_L1_GTVS:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[L1+GTV(S)]"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 0
  weighing: 'size_normalized_inv'
  err_tol: 0.005
  max_iter: 500 # 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config:
  - graph: 'spatial'
    mode : [1]
    p: 2
    variation_type: GTV
    normalization: 'out_degree'
SNN_L1_GTVS_sn:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[L1+GTV(S)]_sn"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 0
  weighing: 'size_normalized'
  err_tol: 0.005
  max_iter: 500 # 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config:
  - graph: 'spatial'
    mode : [1]
    p: 2
    variation_type: GTV
    normalization: 'none'
SNN_L1_GTVS_sn: # Size normalized 
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[L1+GTV(S)]_sn"
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 0
  weighing: 'size_normalized'
  err_tol: 0.005
  max_iter: 500 # 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config:
  - graph: 'spatial'
    mode : [1]
    p: 2
    variation_type: GTV
    normalization: 'out_degree'

SNN_LOGNST_GTV_T:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[LOGN(ST)+GTV(T)]"
  lr_modes: [1, 2, 3]
  graph_modes: [1,3]
  graph: 'spatio-temporal'
  grouping: 'neighbor'
  r_hop: 1
  weighing: 'size_normalized_inv'
  err_tol: 0.1
  max_iter: 150
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: [] 
  gtvr_config:
    - graph: 'temporal'
      mode : [3]
      p: 1
      variation_type: GTV
      normalization: 'none'
SNN_LOGN_F:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[LOGN(S-N)]-f"
  soft_constrained: True
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 1
  weighing: 'size_normalized'
  err_tol: 0.05
  max_iter: 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config: []
  hyperparameters:
    lda_f: 1.0
SNN_LOGN_SN_GTV_T_F:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[LOGN(S-N)+GTV(T)]-f"
  soft_constrained: True
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 1
  weighing: 'size_normalized'
  err_tol: 0.05
  max_iter: 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config:
    - graph: 'temporal'
      mode : [4]
      p: 1
      variation_type: GTV
      normalization: 'none'
  hyperparameters:
    lda_f: 1.0
SNN_LOGNTE_F:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[LOGN(T-E)]-f"
  soft_constrained: True
  lr_modes: [1, 2, 3, 4]
  graph_modes: [4]
  graph: 'temporal'
  grouping: 'edge'
  r_hop: 1
  weighing: 'size_normalized'
  err_tol: 0.05
  max_iter: 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config: []
  hyperparameters:
    lda_f: 1.0
SNN_L1_GTV_T_F:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[L1+GTV(T)]-f"
  soft_constrained: True
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 0
  soft_constrained: False
  weighing: 'size_normalized'
  err_tol: 0.05
  max_iter: 5000
  rho_update: 'domain_parametrization'
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: ~
  hyperparameters:
    lda_f: 1.0
  gtvr_config:
    - graph: 'temporal'
      mode : [4]
      p: 1
      variation_type: GTV
      normalization: 'none'
SNN_LOGNST_F:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[LOGN(ST-N)]-f"
  soft_constrained: True
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1,4]
  graph: 'spatio-temporal'
  grouping: 'neighbor'
  r_hop: 1
  weighing: 'size_normalized'
  err_tol: 0.05
  max_iter: 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  gtvr_config: []
  hyperparameters:
    lda_f: 1.0
SNN_L1_GTVS_F:
  model: "SNN_LOGN_GTV"
  name: "[SNN]-[L1+GTV(S)]-f"
  soft_constrained: True
  lr_modes: [1, 2, 3, 4]
  graph_modes: [1]
  graph: 'spatial'
  grouping: 'neighbor'
  r_hop: 0
  weighing: 'size_normalized'
  err_tol: 0.05
  max_iter: 5000
  rho_update: 1
  rho_update_thr: 100
  verbose: 0
  lda_gtvs: []
  hyperparameters:
    lda_f: 1.0
  gtvr_config:
  - graph: 'spatial'
    mode : [1]
    p: 2
    variation_type: GTV
    normalization: 'none'