# Default Experiment Configuration for GTV-EXP-2
project_name: 'AD_Journal_Experiments'
group_name: 'gtv_exp_2'
config_name: 'default'
tags: []
notes: 'Description of the experiment

--------------------------

Experiment designed to determine the effect of varying radius of anomalies.
'
# results_csv_path: 'results/gtv_exp_1_default.csv'
data:
  lowrank:
    dim: [225, 50, 24]
    ranks: [15, 15, 15]
    # std: 1.0
  graph:
    type: "grid"
    n: 15
    m: 15
    periodic: false
    seed: 0
  anomaly:
    num_anomalies: 500
    amplitude: 0.25
    duration: 1
    window_type: 'boxcar' #'cosine', 'boxcar'
    distribution: 'bernoulli'
    local_dist: 'constant'
    time_m: 3
    local_m: 1
    radius: 1
    anomaly_spread: 'isotropic'
  noise:
    type: 'AWGN'
    SNR: 30
independent_var:
  keys: ['anomaly', 'radius']
  range: [0, 1, 2, 3]
dependent_var:
  - AUC-PRC
  - AUC-ROC
  - S_err
  - L_err
study_config:
  metrics: ['AUC-ROC', 'AUC-PRC']
  overwrite: True
  directions: ['maximize', 'maximize']
  n_trials: 70
  lda_gtv_min: 0.00000001
  lda_gtv_max: 10
  lda_gtv_log: True
models:
  HoRPCA:
    model: "HoRPCA"
    name: "HoRPCA"
    lr_modes: [1, 2, 3]
    err_tol: 1.0e-6
    maxit: 100
    rho_update: 1
    mu: 100
    verbose: 0
  SNN_L1_GTV_ST:
    model: "SNN_LOGN_GTV"
    name: "[SNN]-[L1+GTV(S)]"
    lr_modes: [1, 2, 3]
    graph_modes: [1]
    graph: 'spatial'
    grouping: 'neighbor'
    r_hop: 0
    weighing: 'size_normalized_inv'
    err_tol: 1.0e-6
    max_iter: 100
    rho_update: 1
    rho_update_thr: 100
    verbose: 0
    lda_gtvs: [] 
    gtvr_config:
      - graph: 'spatial'
        mode : [1]
        p: 2
        variation_type: GTV
  SNN_LOGN:
    model: "SNN_LOGN_GTV"
    name: "[SNN]-[LOGN(S-N)]"
    lr_modes: [1, 2, 3]
    graph_modes: [1]
    graph: 'spatial'
    grouping: 'neighbor'
    r_hop: 1
    weighing: 'size_normalized_inv'
    err_tol: 1.0e-6
    max_iter: 100
    rho_update: 1
    rho_update_thr: 100
    verbose: 0
    lda_gtvs: []
    gtvr_config: []
  SNN_LOGN:
    model: "SNN_LOGN_GTV"
    name: "[SNN]-[LOGN(S-N)+GTV(S)]"
    lr_modes: [1, 2, 3]
    graph_modes: [1]
    graph: 'spatial'
    grouping: 'neighbor'
    r_hop: 1
    weighing: 'size_normalized_inv'
    err_tol: 1.0e-6
    max_iter: 100
    rho_update: 1
    rho_update_thr: 100
    verbose: 0
    lda_gtvs: []
    gtvr_config:
      - graph: 'spatial'
        mode : [1]
        p: 2
        variation_type: GTV