# Default Experiment Configuration for GTV-EXP-1
project_name: 'AD_Journal_Experiments'
group_name: 'duration_exp'
config_name: 'temporal_grouped_SL_err'
tags: ['28SNR', 'temporally_grouped', 'SL_err', 'repeated']
notes: 'Description of the experiment

--------------------------

Experiment designed to determine the effect of varying duration of anomalies.
'
# results_csv_path: 'results/gtv_exp_1_default.csv'
data:
  lowrank:
    dim: [225, 50, 24]
    ranks: [30, 20, 15]
    # std: 1.0
  graph:
    type: "grid"
    n: 15
    m: 15
    periodic: false
    seed: 0
  anomaly:
    num_anomalies: 2400
    amplitude: 0.125
    duration: 1
    window_type: 'boxcar' #'cosine', 'boxcar'
    distribution: 'uniform'
    local_dist: 'bernoulli'
    time_m: 3
    local_m: 1
    radius: 0 #2 # was 2
    anomaly_spread: 'isotropic'
  repeated: 1
  noise:
    type: 'AWGN'
    SNR: 28
independent_var:
  keys: ['anomaly', 'duration']
  range: [1, 2, 3, 4, 6, 8, 10, 12] # [1, 3, 5, 7, 9, 11, 13, 15]
dependent_var:
  - AUC-PRC
  - AUC-ROC
  - S_err
  - L_err
  - rel_err
study_config:
  metrics: ['max_SL_rel_err']
  overwrite: True
  directions: ['minimize']
  n_trials: 1000
  lda_gtv_min: 0.00001
  lda_gtv_max: 10
  lda_gtv_log: True
  search_rho: False
  # rho_min: 0.0001
  # rho_max: 10
  # rho_log: True
models:
  HORPCA_F:
    model: "SNN_LOGN_GTV"
    name: "HoRPCA-f"
    soft_constrained: True
    lr_modes: [1, 2, 3]
    graph_modes: [1]
    graph: 'spatial'
    grouping: 'neighbor'
    r_hop: 0
    weighing: 'size_normalized_inv'
    err_tol: 0.1
    max_iter: 150
    rho_update: 'domain_parametrization'
    rho_update_thr: 100
    verbose: 0
    lda_gtvs: []
    gtvr_config: []
  SNN_LOGNTE_F:
    model: "SNN_LOGN_GTV"
    name: "[SNN]-[LOGN(T-E)]-f"
    soft_constrained: True
    lr_modes: [1, 2, 3]
    graph_modes: [3]
    graph: 'temporal'
    grouping: 'edge'
    r_hop: 1
    weighing: 'size_normalized_inv'
    err_tol: 0.1
    max_iter: 150
    rho_update: 'domain_parametrization'
    rho_update_thr: 100
    verbose: 0
    lda_gtvs: []
    gtvr_config: []
  SNN_L1_GTVT_F:
    model: "SNN_LOGN_GTV"
    name: "[SNN]-[L1+GTV(T)]-f"
    soft_constrained: True
    lr_modes: [1, 2, 3]
    graph_modes: [1]
    graph: 'spatial'
    grouping: 'neighbor'
    r_hop: 0
    weighing: 'size_normalized_inv'
    err_tol: 0.1
    max_iter: 150
    rho_update: 'domain_parametrization'
    rho_update_thr: 100
    verbose: 0
    lda_gtvs: [] 
    gtvr_config:
      - graph: 'temporal'
        mode : [3]
        p: 1
        variation_type: GTV
        normalization: 'none'
  SNN_LOGNTE_GTVT_F:
    model: "SNN_LOGN_GTV"
    name: "[SNN]-[LOGN(T-E)+GTV(T)]-f"
    soft_constrained: True
    lr_modes: [1, 2, 3]
    graph_modes: [3]
    graph: 'temporal'
    grouping: 'edge'
    r_hop: 1
    weighing: 'size_normalized_inv'
    err_tol: 0.1
    max_iter: 150
    rho_update: 'domain_parametrization'
    rho_update_thr: 100
    verbose: 0
    lda_gtvs: []
    gtvr_config:
      - graph: 'temporal'
        mode : [3]
        p: 1
        variation_type: GTV
        normalization: 'none'