# LR-S.Sparse Exp 2a Identifiability (HP) Study
# This experiment is to study the identifiability of the hyperparameters of the HoRPCA and SNN-LOGS models

data:
  lowrank:
    dim: [100, 50, 24]
    ranks: [5, 5, 5]
    # std: 1.0
  graph:
    type: "grid"
    n: 10
    m: 10
    periodic: false
    seed: 0
  anomaly:
    num_anomalies: 250
    amplitude: 0.25
    duration: # Chi-square distribution with 5 degrees of freedom. Median: 1+4.362524005486969
      p: [0.08098461488271529, 0.1389313557676891, 0.15480676007142893, 0.14456088070671338, 0.1225373725580454, 0.09769969143510356, 0.07467343605251257, 0.05533587926436772, 0.04004869396684557, 0.028449677829209572, 0.019907610705121682, 0.013757982093840092, 0.00940915576803444, 0.006377940192161188, 0.004290204919427112, 0.002866644781700573, 0.0019042328289326515, 0.00125836949800497, 0.0008277183542461348, 0.0005421880441666958, 0.0003538234756754394, 0.0002301147634342631, 0.00014919524238897748, 9.64567982346814e-05]
      d: [1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
    radius: 2
    window_type: 'boxcar' # 'taylor', 'cosine'
    distribution: 'uniform'
    local_dist: 'constant'
    time_m: 3
    local_m: 1
    anomaly_spread: 'isotropic'
  noise:
    type: 'AWGN'
    SNR: 10
independent_var:
  t:
    min: 0
    max: 1
    resolution: 50
  # window_types:
  #   - 'boxcar'
  #   - 'taylor'
  #   - 'cosine'
models:
  HoRPCA:
    model: "HoRPCA"
    name: "HoRPCA"
    lr_modes: [1, 2, 3]
    err_tol: 1.0e-6
    maxit: 150
    rho_update: 1
    mu: 100
    verbose: 0
  SNN_LOGS:
    model: "SNN_LOGS"
    name: "[SNN]-[LOGN(N)]"
    lr_modes: [1, 2, 3]
    graph_modes: [1]
    grouping: 'neighbor'
    r_hop: 1
    weighing: 'size_normalized_inv'
    err_tol: 1.0e-6
    max_iter: 150
    rho_update: 1
    rho_update_thr: 100
    verbose: 0
  SNN_GTV_T:
    model: "SNN_LOGN_GTV"
    name: "[SNN]-[Temporal GV]"
    lr_modes: [1, 2, 3]
    graph_modes: [1]
    grouping: 'neighbor'
    r_hop: 1
    weighing: 'size_normalized_inv'
    err_tol: 1.0e-6
    max_iter: 150
    rho_update: 1
    rho_update_thr: 100
    verbose: 0
    lda_gtvs: [0, 0, 0] # Not used in the first step
    gtvr_config: #[ ]
      - graph: 'temporal'
        mode: [3]
        variation_type: 'GTV'
        p: 2
        normalization: 'out_degree'
      - graph: 'temporal'
        mode: [3]
        variation_type: 'GTMV'
        p: 1
        normalization: 'right_normalized'
      - graph: 'temporal'
        mode: [3]
        variation_type: 'GTV'
        p: 1
        normalization: 'out_degree'
  SNN_GTV_S:
    model: "SNN_LOGN_GTV"
    name: "[SNN]-[Spatial GV]"
    lr_modes: [1, 2, 3]
    graph_modes: [1]
    grouping: 'neighbor'
    r_hop: 1
    weighing: 'size_normalized_inv'
    err_tol: 1.0e-6
    max_iter: 150
    rho_update: 1
    rho_update_thr: 100
    verbose: 0
    lda_gtvs: [0, 0, 0] # Not used in the first step
    gtvr_config: #[ ]
      - graph: 'spatial'
        mode: [1]
        variation_type: 'GTV'
        p: 2
        normalization: 'out_degree'
      - graph: 'spatial'
        mode: [1]
        variation_type: 'GTMV'
        p: 1
        normalization: 'right_normalized'
      - graph: 'spatial'
        mode: [1]
        variation_type: 'GTV'
        p: 1
        normalization: 'out_degree'
  # SNN_LOGN_GTV_2:
  #   model: "SNN_LOGN_GTV"
  #   name: "[SNN]-[LOGN(N)+GTV(1)]"
  #   lr_modes: [1, 2, 3]
  #   graph_modes: [1]
  #   grouping: 'neighbor'
  #   r_hop: 1
  #   weighing: 'size_normalized_inv'
  #   err_tol: 1.0e-6
  #   max_iter: 150
  #   rho_update: 1
  #   rho_update_thr: 100
  #   verbose: 0
  #   gtvr_config:
  #     - graph': 'temporal'
  #       mode: [3]
  #       variation_type: 'GTMV'
  #       p: 1
  #       normalization: 'right_normalized'
  # SNN_LOGN_GTV_3:
  #   model: "SNN_LOGN_GTV"
  #   name: "[SNN]-[LOGN(N)+GTMV]"
  #   lr_modes: [1, 2, 3]
  #   graph_modes: [1]
  #   grouping: 'neighbor'
  #   r_hop: 1
  #   weighing: 'size_normalized_inv'
  #   err_tol: 1.0e-6
  #   max_iter: 150
  #   rho_update: 1
  #   rho_update_thr: 100
  #   verbose: 0
  #   gtvr_config:
  #     - graph: 'temporal'
  #       mode: [3]
  #       variation_type: 'GTMV'
  #       p: 1
  #       normalization: 'right_normalized'
dependent_vars:
  - AUC-ROC
  - AUC-PRC
  - S-LV-1-median
  - S-LV-1-q1
  - S-LV-1-q3
  - S-LV-1-upper_fence
  - S-LV-2-median
  - S-LV-2-q1
  - S-LV-2-q3
  - S-LV-2-upper_fence
  - S-LV-3-median
  - S-LV-3-q1
  - S-LV-3-q3
  - S-LV-3-upper_fence
  - S_diff
  - L_diff
  - L_nuc_1
  - L_nuc_2
  - L_nuc_3
  - S_nuc_1
  - S_nuc_2
  - S_nuc_3
  - L_nuc_1_eps
  - L_nuc_2_eps
  - L_nuc_3_eps
  - S_nuc_1_eps
  - S_nuc_2_eps
  - S_nuc_3_eps
  - L1
  - L1_eps
  - S1
  - S1_eps
  - nonzero_S
  - nonzero_L
  - ranks_S1
  - ranks_S2
  - ranks_S3
  - ranks_L1
  - ranks_L2
  - ranks_L3
  - S_fro
  - L_fro
  - L_fro_eps
  - S_fro_eps
  - S_err
  - L_err
  - tol
  - diff